### ISSUE TITLE
Traverso DAW 

### ISSUE THREAD

**Issue by Reaper10** [ErwanLegrand/Traverso-DAW#1]
Is Traverso DAW  dead?

**Comment by ErwanLegrand** [comment]
I think it is. This is the very reason why I made this clone.

**Comment by Reaper10** [comment]
are you still working on, it if you are here is a mixer gui idea I had

![traverso daw mixer](https://cloud.githubusercontent.com/assets/8137561/15630981/99802740-2517-11e6-9a19-b85c41c150d3.jpg)
here is a synth you look in to as a built in http://tytel.org/helm/    https://github.com/mtytel/helm

**Comment by rsijrier** [comment]
Traverso development has been on hold for a long time, recently the website has been restored and work is in progress for the next release which we think is a significant improvement over the last stable release
Help of course (in any form) is much appreciated....

http://traverso-daw.org
irc #traverso

Regards,
Traverso team

**Comment by ErwanLegrand** [comment]
These are great news! Thanks for letting us know, @rsijrier!

For those looking for it, the official git repository is here: https://savannah.nongnu.org/git/?group=traverso
