### ISSUE TITLE
new daw software

### ISSUE THREAD

**Issue by Reaper10** [ErwanLegrand/Traverso-DAW#2]
I think it's sad see all these daws on here just die I think someone should combined the code and bring them back from the dead in the dead in the form a new and better daw

here the two daw that I'm talking about I'm not a coder

https://github.com/hirano/koblo_software
https://github.com/zuoteng/koblo_software
https://github.com/ErwanLegrand/Traverso-DAW

**Comment by ErwanLegrand** [comment]
Traverso DAW is back from the dead! See the official website: https://traverso-daw.org/
